import {
  CodeTableProps,
  DepartmentProps,
  Payment,
  ProfileTabProps,
} from "./types";
import { CgSmartHomeRefrigerator } from "react-icons/cg";
import { GrServices } from "react-icons/gr";
import { BsShop } from "react-icons/bs";
import { TbAirConditioning } from "react-icons/tb";
import { FaGripfire } from "react-icons/fa";
import { PiMathOperationsBold } from "react-icons/pi";
import { LiaFileContractSolid } from "react-icons/lia";

export const Departments: DepartmentProps[] = [
  {
    url: "it",
    label: "IT",
    value: "IT",
    icon: LiaFileContractSolid,
    catalyst: "Don Denver Juaneza",
  },
  {
    url: "refrigeration",
    label: "Refrigeration",
    value: "Refrigeration",
    icon: CgSmartHomeRefrigerator,
    catalyst: "Unknown",
  },
  {
    url: "service",
    label: "Service",
    value: "Service",
    icon: GrServices,
    catalyst: "Unknown",
  },
  {
    url: "shopfitting-and-warehouse-racking",
    label: "Shopfitting and Warehouse Racking",
    value: "Shopfitting and Warehouse Racking",
    icon: BsShop,
    catalyst: "Unknown",
  },
  {
    url: "hvac",
    label: "HVAC",
    value: "HVAC",
    icon: TbAirConditioning,
    catalyst: "Unknown",
  },
  {
    url: "mepfs",
    label: "MEPFS",
    value: "MEPFS",
    icon: FaGripfire,
    catalyst: "Unknown",
  },
  {
    url: "cons-operations",
    label: "CONS - Operations",
    value: "CONS - Operations",
    icon: PiMathOperationsBold,
    catalyst: "Unknown",
  },
  {
    url: "cons-document-billing-and-contracts",
    label: "CONS - Document, Billing and Contracts",
    value: "CONS - Document, Billing and Contracts",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-document-management",
    label: "CONS - Document Management",
    value: "CONS - Document Management",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-cost-control",
    label: "CONS - Cost Control",
    value: "CONS - Cost Control",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-tsg",
    label: "CONS - TSG",
    value: "CONS - TSG",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-tender",
    label: "CONS - Tender",
    value: "CONS - Tender",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-qaqc",
    label: "CONS - QAQC",
    value: "CONS - QAQC",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-formworks",
    label: "CONS - Formworks",
    value: "CONS - Formworks",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-rebar",
    label: "CONS - Rebar",
    value: "CONS - Rebar",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-foundation",
    label: "CONS - Foundation",
    value: "CONS - Foundation",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "cons-equipment",
    label: "CONS - Equipment",
    value: "CONS - Equipment",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "management-accounting",
    label: "Management Accounting",
    value: "Management Accounting",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "treasury",
    label: "Treasury",
    value: "Treasury",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "audit",
    label: "Audit",
    value: "Audit",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "human-resources",
    label: "Human Resources",
    value: "Human Resources",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "ehs",
    label: "EHS",
    value: "EHS",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "strategic-business-growth",
    label: "Strategic Business Growth",
    value: "Strategic Business Growth",
    icon: LiaFileContractSolid,
    catalyst: "Danilo Franco",
  },
  {
    url: "government-relations",
    label: "Government Relations",
    value: "Government Relations",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "importation",
    label: "Importation",
    value: "Importation",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "purchasing",
    label: "Purchasing",
    value: "Purchasing",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
  {
    url: "warehouse-and-logistics",
    label: "Warehouse & Logistics",
    value: "Warehouse & Logistics",
    icon: LiaFileContractSolid,
    catalyst: "Unknown",
  },
];

export const payments: Payment[] = [
  {
    id: "1",
    assigned_to: "Bry",
    status: "open",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "2",
    assigned_to: "Tyrone",
    status: "close",
    created_at: "09-28-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "3",
    assigned_to: "Bry",
    status: "expired",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "4",
    assigned_to: "Tyrone",
    status: "re-opened",
    created_at: "09-30-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "5",
    assigned_to: "Zeth",
    status: "re-opened",
    created_at: "09-23-2023",
    name: "Chona Mae",
    subject: "My mouse run away",
  },
  {
    id: "6",
    assigned_to: "Bry",
    status: "open",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "7",
    assigned_to: "Tyrone",
    status: "close",
    created_at: "09-28-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "8",
    assigned_to: "Bry",
    status: "expired",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "9",
    assigned_to: "Tyrone",
    status: "re-opened",
    created_at: "09-30-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "10",
    assigned_to: "Zeth",
    status: "re-opened",
    created_at: "09-23-2023",
    name: "Chona Mae",
    subject: "My mouse run away",
  },
  {
    id: "11",
    assigned_to: "Bry",
    status: "open",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "12",
    assigned_to: "Tyrone",
    status: "close",
    created_at: "09-28-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "13",
    assigned_to: "Bry",
    status: "expired",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "14",
    assigned_to: "Tyrone",
    status: "re-opened",
    created_at: "09-30-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "15",
    assigned_to: "Zeth",
    status: "re-opened",
    created_at: "09-23-2023",
    name: "Chona Mae",
    subject: "My mouse run away",
  },
  {
    id: "16",
    assigned_to: "Bry",
    status: "open",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "17",
    assigned_to: "Tyrone",
    status: "close",
    created_at: "09-28-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "18",
    assigned_to: "Bry",
    status: "expired",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "19",
    assigned_to: "Tyrone",
    status: "re-opened",
    created_at: "09-30-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "20",
    assigned_to: "Zeth",
    status: "re-opened",
    created_at: "09-23-2023",
    name: "Chona Mae",
    subject: "My mouse run away",
  },
  {
    id: "1",
    assigned_to: "Bry",
    status: "open",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "2",
    assigned_to: "Tyrone",
    status: "close",
    created_at: "09-28-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "3",
    assigned_to: "Bry",
    status: "expired",
    created_at: "09-28-2023",
    name: "Daniel Rey",
    subject: "My mouse run away",
  },
  {
    id: "4",
    assigned_to: "Tyrone",
    status: "re-opened",
    created_at: "09-30-2023",
    name: "David Domanais",
    subject: "My mouse run away",
  },
  {
    id: "5",
    assigned_to: "Zeth",
    status: "re-opened",
    created_at: "09-23-2023",
    name: "Chona Mae",
    subject: "My mouse run away",
  },
  // ...
];
